[project]
name = "repo-template"
dynamic = ["version"]
requires-python = ">=3.10"

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0",
    "ruff>=0.6.0",
    "mypy>=1.11.0",
    "pip-audit>=2.7.0",
]

[tool.pytest.ini_options]
pythonpath = "."
