name: CI
on:
  pull_request:
  push:
    branches: [main]
permissions: { contents: read }
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - run: uv sync --dev
      - run: uv run pip-audit
      - run: uv run ruff check --output-format=github .
      - run: uv run mypy .

  tests:
    runs-on: windows-latest
    strategy:
      matrix: { python-version: ["3.9", "3.10","3.11","3.12","3.13","3.14"] }
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - run: uv sync --dev
      - run: uv run pytest -q --maxfail=1 --disable-warnings --cov --cov-report=xml