name: Security
on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 3 * * 1"  # Mondays 03:00 UTC
permissions:
  contents: read
  security-events: write
concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: github/codeql-action/init@v4
        with:
          languages: python
      - uses: github/codeql-action/analyze@v4
